### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by augnustin** [kjohnston/pgbackups-archive#22]
Hey,

First issue here, waou. 
I'm really interested into using this gem/app but unfortunately, I can't make it work.

Quick steps:
I've followed all the points mentionned in the readme.md as with the external app. 

I still get this error:

```
$ backup run rake pgbackups:archive      
Running `rake pgbackups:archive` attached to terminal... up, run.8035
** [NewRelic][09/19/13 21:57:52 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] INFO : Starting the New Relic agent in "development" environment.
** [NewRelic][09/19/13 21:57:52 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] INFO : To prevent agent startup add a NEWRELIC_ENABLE=false environment variable or modify the "development" section of your newrelic.yml.
** [NewRelic][09/19/13 21:57:52 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] INFO : Reading configuration from config/newrelic.yml
** [NewRelic][09/19/13 21:57:52 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] INFO : Disabling the Request Sampler.
** [NewRelic][09/19/13 21:57:52 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] WARN : Agent is configured not to use SSL when communicating with New Relic's servers
** [NewRelic][09/19/13 21:57:52 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] INFO : Environment: development
** [NewRelic][09/19/13 21:57:52 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] INFO : No known dispatcher detected.
** [NewRelic][09/19/13 21:57:52 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] INFO : Application: copass-backup
** [NewRelic][09/19/13 21:57:52 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] INFO : Installing Net instrumentation
** [NewRelic][09/19/13 21:57:52 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] INFO : Finished instrumentation
** [NewRelic][09/19/13 21:57:52 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] INFO : Reporting to: https://rpm.newrelic.com/accounts/430318/applications/2119748
** [NewRelic][09/19/13 21:57:52 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] INFO : Starting the New Relic agent in "development" environment.
** [NewRelic][09/19/13 21:57:52 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] INFO : To prevent agent startup add a NEWRELIC_ENABLE=false environment variable or modify the "development" section of your newrelic.yml.
** [NewRelic][09/19/13 21:57:52 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] INFO : Reading configuration from config/newrelic.yml
.rake aborted!
404 Resource Not Found
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/rest-client-1.6.7/lib/restclient/resource.rb:51:in `get'
/app/vendor/bundle/ruby/2.0.0/gems/heroku-2.34.0/lib/heroku/client/pgbackups.rb:70:in `block in get'
/app/vendor/bundle/ruby/2.0.0/gems/heroku-2.34.0/lib/heroku/client/pgbackups.rb:93:in `check_errors'
/app/vendor/bundle/ruby/2.0.0/gems/heroku-2.34.0/lib/heroku/client/pgbackups.rb:69:in `get'
/app/vendor/bundle/ruby/2.0.0/gems/heroku-2.34.0/lib/heroku/client/pgbackups.rb:36:in `get_transfer'
/app/vendor/bundle/ruby/2.0.0/gems/pgbackups-archive-0.2.0/lib/pgbackups-archive/heroku/client/pgbackups_archive.rb:33:in `capture'
/app/vendor/bundle/ruby/2.0.0/gems/pgbackups-archive-0.2.0/lib/pgbackups-archive/heroku/client/pgbackups_archive.rb:10:in `perform'
/app/Rakefile:9:in `call'
(eval):3:in `block in call_with_newrelic_transaction_trace'
/app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.3.111/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:318:in `perform_action_with_newrelic_trace'
(eval):2:in `call_with_newrelic_transaction_trace'
/app/Rakefile:19:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
Tasks: TOP => pgbackups:archive
(See full trace by running task with --trace)
** [NewRelic][09/19/13 21:57:55 +0000 0db350d9-dfb0-4e35-8042-cd74310ccf8f (2)] INFO : Starting Agent shutdown

```

I have tried with ENV variables configs, and with straight newrelic.yml config. Here's my `config/newrelic.yml` file

```
production:
  error_collector:
    capture_source: true
    enabled: true
    ignore_errors: ActionController::RoutingError
  apdex_t: 0.5
  ssl: false
  monitor_mode: true
  license_key: <licence_key>
  developer_mode: false
  app_name: <app_name>
  transaction_tracer:
    record_sql: obfuscated
    enabled: true
    stack_trace_threshold: 0.5
    transaction_threshold: apdex_f
  capture_params: false
  log_level: info
development:
  error_collector:
    capture_source: true
    enabled: true
    ignore_errors: ActionController::RoutingError
  apdex_t: 0.5
  ssl: false
  monitor_mode: true
  license_key: <licence_key>
  developer_mode: true
  app_name: <licence_key>
  transaction_tracer:
    record_sql: obfuscated
    enabled: true
    stack_trace_threshold: 0.5
    transaction_threshold: apdex_f
  capture_params: false
  log_level: info

```

And maybe I made a mistake in `ENV['PGBACKUPS_DATABASE_URL']` I've set my `ENV['PGBACKUPS_URL']` from the original app. Is that right?

And my last question is about bucket CORS, shouldn't I set something specific here.
I've allowed GET and POST to the bucket from http://app_name.herokuapp.com but it could not make any sense.

If you could help, it would be awesome, I'm really interested into having manual backups.
